// <auto-generated />
using System;
using EFCF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCF.Migrations
{
    [DbContext(typeof(EmployeeManagement))]
    partial class EmployeeManagementModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCF.Model.Dept", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Deptno");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("EFCF.Model.Emp", b =>
                {
                    b.Property<int>("Empno")
                        .HasColumnType("int");

                    b.Property<string>("Addr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deptno")
                        .HasColumnType("int");

                    b.Property<int?>("DeptnoNavDeptno")
                        .HasColumnType("int");

                    b.Property<string>("Ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Empno");

                    b.HasIndex("DeptnoNavDeptno");

                    b.ToTable("Emps");
                });

            modelBuilder.Entity("EFCF.Model.Emp", b =>
                {
                    b.HasOne("EFCF.Model.Dept", "DeptnoNav")
                        .WithMany("Emps")
                        .HasForeignKey("DeptnoNavDeptno");

                    b.Navigation("DeptnoNav");
                });

            modelBuilder.Entity("EFCF.Model.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
